version: '2.1'

services:
  go-html:
    image: go-html
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VIRTUAL_HOST: listabird.com, www.listabird.com, wwwlocal.listabird.com
      VIRTUAL_PORT: 80
    ports:
      - 7065:7065
    volumes:
      - ~/listabird/www/static:/go/src/go-html-boilerplate/static:ro
      - ~/listabird/www/templates:/go/src/go-html-boilerplate/templates:ro
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports: 
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro